app:
  name: currency-telegram-bot
server:
  port: 8080
spring:
  application:
    name: ${app.name}
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=600s # время жизни значения после последнего обращения к нему
bot:
  name: "Курсы валют 💸"
client:
  rest:
    cbr:
      url: "https://www.cbr-xml-daily.ru/daily_utf8.xml"
    api-layer:
      url: "https://api.apilayer.com"
    crypto-compare:
      url: "https://min-api.cryptocompare.com"
logging:
  level:
    root: info